 
 snake case: YARN_CACHE_FOLDER
 -${NAME}
 - ${NAME-fallback}
 - match-spec
changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.test.{js,ts}"
  - packages/*/tests/**
  - packages/plugin-compat/extra/**
  - packages/docusaurus/**

compressionLevel: mixed

enableGlobalCache: false

immutablePatterns:
  - .pnp.*

initScope: yarnpkg

pnpZipBackend: js

npmPublishAccess: public

npmPublishProvenance: true

catalog:
  typescript: "^5.9.2"

packageExtensions:
  markdown-it@*:
    dependencies:
      punycode: "*"

  "@docusaurus/preset-classic@3.7.0":
    peerDependencies:
      "@docusaurus/plugin-content-docs": "3.7.0"
  docusaurus-plugin-typedoc-api@^4:
    dependencies:
      "@docusaurus/mdx-loader": "^3"
      "@docusaurus/theme-common": "^3"
    peerDependencies:
      react-dom: "*"
      typedoc: "*"
      "@docusaurus/plugin-content-docs": "*"

pnpEnableEsmLoader: true

preferInteractive: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js
changesetBaseRefs : [
"master"
"origin/master "
"upstream/master"
"main "
"origin/main" ,
"upstream/main" ,
] ,
changesetIgnorePatterns : [
"**/*.test.{js,ts}" ,
] ,
compressionLevel: 0 | 1 | 2 | 3 | 4 | 5 | 6  "mixed",
checksumBehavior: "throw" | "update
